### ISSUE TITLE
non ascii (english) languages 

### ISSUE THREAD

**Issue by alexmyczko** [rmcmulli-rh/bwht-fonts#1]
do you plan to add accented and non latin language support to these fonts?

```
for a in *.otf; do glyphcount.pl $a; done
    97  because-we-build.otf
   124  because-we-connect.otf
   123  because-we-create.otf
    97  because-we-learn.otf
   125  because-we-mentor.otf
   126  because-we-organize.otf
```

**Comment by rmcmulli-rh** [comment]
We're not currently working on adding additional glyphs, but we are happy to review and accept patches for additional glyphs that come from outside contributors.
